#This code creates plots in two rows and two columns
Data_source <- "~/Desktop/coursera/EDA/proj1/household_power_consumption.txt"
Data <- read.table(Data_source, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
Sub_Data <- Data[Data$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(Sub_Data$Date, Sub_Data$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
GlobalActivePower <- as.numeric(Sub_Data$Global_active_power)
GlobalReactivePower <- as.numeric(Sub_Data$Global_reactive_power)
voltage <- as.numeric(Sub_Data$Voltage)
subMetering1 <- as.numeric(Sub_Data$Sub_metering_1)
subMetering2 <- as.numeric(Sub_Data$Sub_metering_2)
subMetering3 <- as.numeric(Sub_Data$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(datetime, GlobalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(datetime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(datetime, subMetering1, type="l", ylab="Energy Sub metering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(datetime, GlobalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
